#====================================================#
#                                                    #
#   $$$$$$$$$$$$$$   $$               $$        $$   #
#   $$               $$                $$      $$    #
#   $$               $$                 $$    $$     ========================================
#   $$               $$                  $$  $$      =       Plugin made with love          =
#   $$$$$$$$$$$      $$                    $$        =            by: Durqznohh             =
#   $$               $$                    $$        =                  <3                  =
#   $$               $$                    $$        ========================================
#   $$               $$                    $$        #
#   $$               $$$$$$$$$$$$$         $$        #
#                                                    #
#====================================================#
#
#
#
#
#