name: SuperFly
version: '1.0'
main: com.durqznohh.superfly
api-version: 1.18
authors: [ Durqznohh ]
description: The best plugin for Fly
commands:
  fly:
    description: Enable or disable fly mode.
  superfly:
    description: Displays all commands.
